angular.module("app", ["ngCookies", "ui.router", "ui.bootstrap"])
    .config(routing)
    .service("sessionService", sessionService)
    .service("userService", userService)
    .service("requestService", requestService)
    .filter("requestStatusFilter", requestStatusFilter)
    .component("ibMain", ibMainComponent)
    .component("ibWelcome", ibWelcomeComponent)
    .component("ibLogin", ibLoginComponent)
    .component("ibRegistration", ibRegistrationComponent)
    .component("createRequest", createRequestComponent)
    .component("requestList", requestListComponent)
    .component("request", requestComponent);